#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export PATH=/usr/local/bin:$PATH

# Editor
export EDITOR=/usr/bin/emacs

# Root Path
export PATH=/Users/jbetz/bin:${PATH}

# arc
export PATH=~/base/phacility/arcanist/bin:$PATH
# source /Users/jbetz/base/phacility/arcanist/resources/shell/bash-completion

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home

