# Disable user autocomplete-- slow with NFS
zstyle ':completion:*' users

# load my functions and completions
fpath=(~/.zprezto/functions $fpath)
autoload -U ~/.zprezto/functions/*(:t)
fpath=(~/.zprezto/completion $fpath)
autoload -U ~/.zprezto/completion/*(:t)

# Custom Autocompletions
# TODO: Where to keep this?
compdef _goenv goenv

# Aliases
alias emacs='emacs -nw'
alias l='ls -lFh'
alias la='ls -lAFh'
alias lr='ls -tRFh'
alias ll='ls -l'
alias zshrc='$EDITOR ~/.zshrc'
alias grep='grep --color'
alias ps="ps -ef"
alias godeps="go list -f '{{ join .Deps  \"\n\"}}' ."

# GVM
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

# Prezto
[[ -s "$HOME/.zprezto/init.zsh" ]] && source "$HOME/.zprezto/init.zsh"

# Solarized
[[ -s "$HOME/.dir_colors/dircolors" ]] && eval `dircolors $HOME/.dir_colors/dircolors`

# Load my profile.
source ~/.zprofile

# Loca my gitignored machine local zshrc
[[ -s "$HOME/.zshrc-local" ]] && source "$HOME/.zshrc-local"

# Powerlevel9k Customizations
powerlevel_setup
