#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
POWERLEVEL9K_MODE='nerdfont-fontconfig'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load my profile.
source ~/.zprofile

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jbetz/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/jbetz/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jbetz/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/jbetz/google-cloud-sdk/completion.zsh.inc'; fi

# https://github.com/ryanoasis/nerd-fonts#option-1-install-script

# 'custom_postfix' Postfix prompt customization
prompt_postfix() {
  echo "\uf0e7"
}

POWERLEVEL9K_CUSTOM_SYMBOL="prompt_postfix"
POWERLEVEL9K_CUSTOM_SYMBOL_BACKGROUND='234'
POWERLEVEL9K_CUSTOM_SYMBOL_FOREGROUND='003'

# 'lnkd' LinkedIn 'in' customization
lnkd() {
  echo '\uf08c' # LinkedinIn 'in'
}

POWERLEVEL9K_CUSTOM_LNKD="lnkd"
POWERLEVEL9K_CUSTOM_LNKD_BACKGROUND='white'
POWERLEVEL9K_CUSTOM_LNKD_FOREGROUND='033'

# MP identifying script
lnkd_mp() {
  local product_spec
  for product_spec_dir in $(upsearch product-spec.json); do
    if [[ "$product_spec_dir" != "/" && "$product_spec_dir" != "$HOME"  ]]; then
       local name=$(jq -r .name $product_spec_dir/product-spec.json)
       local name=$(jq -r .name $product_spec_dir/product-spec.json)
       # echo "\uf08c $name" # LinkedinIn 'in'
       echo "\uf06c $name" # mint leaf
    fi
  done
}

PROMPT=${PWD/#$HOME/~}
mcd() {
  if [ $# -eq 0 ]; then
    local dir
    for dir in $(upsearch product-spec.json); do
      if [[ "$dir" != "/" && "$dir" != "$HOME"  ]]; then
         cd $dir
      else
        echo "Not in an MP."
      fi
    done
  elif [[ $# -gt 0 && $# -lt 3 ]]; then
    local mp_path="$HOME/projects/$1_trunk"
    if [ -d $mp_path ]; then
      if [ $# -eq 1 ]; then
        cd $mp_path
      else
        cd $mp_path/$2
      fi
    else
      echo "MP not found: $1 at $mp_path"
    fi
  else
    echo "Usage: $0 [mp_name [path]]"
  fi
}

POWERLEVEL9K_CUSTOM_MP="lnkd_mp"
POWERLEVEL9K_CUSTOM_MP_BACKGROUND='green'
POWERLEVEL9K_CUSTOM_MP_FOREGROUND='black'

# disabled: go_version - too verbose
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_mp vcs virtualenv context dir)
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=5
POWERLEVEL9K_VCS_GIT_ICON=''

DIR_BACKGROUND='234'
DIR_FOREGROUND='003'
POWERLEVEL9K_DIR_HOME_BACKGROUND=$DIR_BACKGROUND
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=$DIR_BACKGROUND
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=$DIR_BACKGROUND
POWERLEVEL9K_DIR_HOME_FOREGROUND=$DIR_FOREGROUND
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=$DIR_FOREGROUND
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=$DIR_FOREGROUND
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''

DEFAULT_USER=jbetz

POWERLEVEL9K_VCS_CLEAN_BACKGROUND='011'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'

POWERLEVEL9K_SHOW_CHANGESET=true

